baseURL = 'https://thedenisnikulin.github.io/'
languageCode = 'en-us'
title = '🦆✨tinyblog'
theme = 'PaperMod'

[params]
ShowReadingTime = true
# ShowPostNavLinks = true
ShowCodeCopyButtons = true

[params.homeInfoParams]
title = "🦆 tiny writings of rw_panic0_0"
content = 'I sometimes write my thoughts on programming, software design, and life'

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/thedenisnikulin"

[[params.socialIcons]]
name = "Telegram"
url = "https://t.me/rw_panic0_0"
